language: node_js
sudo: false
cache:
  yarn: true
  directories:
  - node_modules
node_js:
- 8.4.0
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
- export PATH="$HOME/.yarn/bin:$PATH"
install:
- yarn install
script:
- yarn test
- yarn build
deploy:
  provider: npm
  email: trevorhartman@gmail.com
  skip_cleanup: true
  api_key:
    secure: PPnJew2JJ+VPOvgATA8noiaL74ZKDOIXkYJnRtppS9v8TWd2WpOrvn1tHLmJmRO3YNCgnbHXI8if5oFnrOBYyFtNkzmoCc0f3OUcCPEqJs+KCnx78rSctHfyjW4kfaeWBMjuOF0WoAa55rX4+qSN8pkWszc79zXirCV+F3dQ2xeujtO6VPWI3vksFa4Mi9tri1MCCW0OPPok2/JYhVCceaD61RrNmzdf6Qp7sjw/ROZIyNlcqBNCQeN7Lk1Ccg1UdMZ7wtHoh/QKQVSkKkd4wmd9glLyCMBue8Fr6jAo7qJoDFD8LADbinuFowH+Kjdw00MC0ShaKT48g849HYGrgApPAxRTQn8gttW2JKyM6XlYKhofIlz0/ydL0d7z0NiB7GbssecI3pVH/Qo4wqlMSvkfF2Xormzm0oGj+1FFYzRBGhyYNvnVBtJH/Hzkp815Zi9fEIJL8MyA/xjGR+knzMYwnyd9FRApgCOD/5magHfY90OxUgK3jbMIziiVXIdR+3LbqlUvOLv68f5g99cFIbYTjd/r59L5azfVZ9jVHLKHkebH6PDL0MMKbTGRw0Gu9xPqVE0iNbUTxo5cZ2VLzKcmv+Uztg99PRDMv0gm80nLwPvj3pIeLtwNZNNgleuOFR4aUHh+mJdsxkgbXihby6PD7/fgqj8FUsnuhbqjadY=
  on:
    tags: true
    repo: yetibot/yetibot-dashboard
