language: node_js
sudo: false
cache:
  yarn: true
  directories:
  - node_modules
node_js:
- 11.15.0
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
- export PATH="$HOME/.yarn/bin:$PATH"
install:
- yarn install
script:
- yarn test
- yarn build
deploy:
  provider: npm
  skip_cleanup: true
  email: trevorhartman@gmail.com
  api_key:
    secure: bEi8Uv6W45i5zAIY0cbEyl2FPGnflDGCnvh7ZmnD+0aKhcR3iJwXI/yAZuW28+fmffYqRAzTz7XTXZDNvgu1CDBzJLt0ZE6LbFhstWlM5Jh5c6ltjEMxq/JoO69HTcFdZTvYLLT0awn2PI+RIcEbkt4q5raeNOz/iR16OhKDqq8IT8E9zIofitU5dE7DNVrtxAVa7CzXDaIma5TNfxbxemAAS+I4AUx0aiFeU3cqWciVftx+ny6SUSFIECb3qZoto93Z/VH8Lt8BF4DyYJFushMlBior3j8S5QpZ2rUvbkm2sI6NuZBwpq6XOJlwB4JesCWXjvWfHN1Hnfz81kGgRvOU7n79++B2Tr4uEfH3/3w/bxtUPBZGr5z9+A7IOb/lW++9MWrc9ZNcvFNFNjndvB/74BvIoDvz5JqmTIF9i4k4amLapNSpqWusuPHrf5yjf2C81BhnZLJhVX1qDjSdcLe5aWugfREe/JDwyyjdKPrMIEjNMVQUgIV5dztftqxiLSwUq2Ux/+OxNc02lPfy4poGyWl1kpZLF0dRddTVF0/LxMWcLu2xnktuwyi0qqPwUVJuh1Gd+yWCIzYTsnRMBy+S6Wo5QxtgHwOI/yavGZepTofyjo+oMlbWwozz/z108+D6unx968JaQ1JbvTuIeoosQCTS0bWubmdaeEApbYo=
  on:
    tags: true
    repo: yetibot/yetibot-dashboard
