language: node_js
sudo: false
cache:
  yarn: true
  directories:
  - node_modules
node_js:
- 8.4.0
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
- export PATH="$HOME/.yarn/bin:$PATH"
install:
- yarn install
script:
- yarn test
- yarn build
deploy:
  provider: npm
  skip_cleanup: true
  email: trevorhartman@gmail.com
  api_key:
    secure: sJq9FXOE5uLXWTxNbFesqvlKql7BFrntDXM+TT3UivQsDE5+pCwRMKNfzWFAPsfqCGoU5U9nqd5eNvG9FfN24fFOM3Xa4S/JNokaH69WSSaUXcS1OHQQyzv2Y9hUssoVPWpACI6i2ojTSpiXdCDV4lOWzkToU+HbwOjx7F1340dzjLwf4iyUK+HmaRKf6UNjOrlmxefg7W4N+cl+DuBdfKbAgnvrJ0/m9V22I5+K6OZyouHbIULEXQsZg6NyCdjC/ALNVv5yWsUR2CUVVcVG+ky2tE5VSbfvpHuTLxJgC6y+VzfUCGdxZmev8sKEoFC4P0jvHkb8wcYcPHoglVR08q2Uj0MBHPwQpYp9OjeZtGhTgcpBb1Z9N/2SzJJY/yX6c1zmK1NmusZnY+WhpW6ucU5nUsgGIzOoequ7ELkLRuleabhmtX2n7tM47IQH9sNpHsUbqOFOw9Hq7mADqQgdZs9/IOHahcWKR7IimpplJnbGAeB1A4cIa8hkDKoD2+WVUMXQA+egg7kHVxvMe2QvIw1R8Qv159XsvWRtzc+kx5hrd0trZcDVCf0KGRmScIOvYVnRyMj5Jsf9CCNwZ8F9BZHrrR/9FoAZY5A0xKPumE2qVEwbgLT65w2RZQ3oOvtm+/EWsRv0czoHoITL3TswJsVK4RMYNU6ke3gf1SS//zg=
  on:
    tags: true
    repo: yetibot/yetibot-dashboard
